package com.customify.client;

// NEW VERSION
public enum Keys {
    LOGIN,
    REGISTER,
    FEEDBACK,
    GET_USERS,
    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    DELETE_PRODUCT,
    GET_PRODUCT_BY_ID,
    CREATE_BUSINESS,
    EDIT_BUSINESS,
    CREATE_CUSTOMER,
    CREATE_PLAN,
    UPDATE_PLAN,
    READ_PLAN,
    DELETE_PLAN
}
