package com.customify.client;

public enum Keys {
    LOGIN,
    REGISTER,
    FEEDBACK,
    GET_USERS,
    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    DELETE_PRODUCT,
    GET_PRODUCT_BY_ID,
    UPDATE_PRODUCT,
    CREATE_BUSINESS,
    REMOVE_BUSINESS,
    GET_ALL_BUSINESSES,
    GET_BUSINESS,
    CREATE_CUSTOMER,
    EDIT_BUSINESS,
<<<<<<< HEAD
<<<<<<< HEAD
=======
    CREATE_CUOPON,
>>>>>>> 7b4a02880ce3083be703a32012a6f90229b7c3ae
=======
>>>>>>> 572e5d1d326f42ffe07c0f5612d5a6434549bf86
    CREATE_PLAN,
    UPDATE_PLAN,
    READ_PLAN,
    DELETE_PLAN,
    ADD_SALE,
    UPDATE_CUSTOMER,
    CREATE_CUOPON,
    REDEEMING_COUPON,
    DISABLE_CUSTOMER,
    CHECK_COUPON;
    CREATE_CUOPON
}
