package com.customify.client;

public enum Keys {
    LOGIN,
    REGISTER,
    FEEDBACK,
    GET_USERS,
    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    DELETE_PRODUCT,
    GET_PRODUCT_BY_ID,
    UPDATE_PRODUCT,
    CREATE_BUSINESS,
    REMOVE_BUSINESS,
    GET_ALL_BUSINESSES,
    GET_BUSINESS,
    CREATE_CUSTOMER,
    EDIT_BUSINESS,
<<<<<<< HEAD
=======
    CREATE_CUOPON,
>>>>>>> 7b4a02880ce3083be703a32012a6f90229b7c3ae
    CREATE_PLAN,
    UPDATE_PLAN,
    READ_PLAN,
    DELETE_PLAN,
    DISABLE_CUSTOMER,
    REDEEMING_COUPON,
    CHECK_COUPON
}
