package com.customify.shared;

public enum Keys {
    LOGIN,
    REGISTER,
    FEEDBACK,
    GET_USERS,
    POINTS_BY_CUSTOMER_EMAIL,
    GET_WINNERS,
    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    DELETE_PRODUCT,
    GET_PRODUT_BY_ID,
    CREATE_BUSINESS,
    CREATE_PLAN,
    UPDATE_PLAN,
    READ_PLAN,
    DELETE_PLAN
}
