package com.customify.shared;

public enum Keys {
    LOGIN,
    REGISTER,
    FEEDBACK,
    GET_USERS,
    POINTS_BY_CUSTOMER_EMAIL,
    GET_WINNERS,
    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    DELETE_PRODUCT,
    GET_PRODUCT_BY_ID,
    CREATE_BUSINESS,
    GET_BUSINESS,
    GET_BUSS_BY_ID,
    REMOVE_BUSINESS,
    GET_ALL_BUSINESSES,
}
