package com.customify.server;

public enum Keys {
    LOGIN,
    REGISTER,
    FEEDBACK,
    GET_USERS,
    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    DELETE_PRODUCT,
    GET_PRODUCT_BY_ID,
    UPDATE_PRODUCT,
    CREATE_BUSINESS,
    REMOVE_BUSINESS,
    GET_ALL_BUSINESSES,
    GET_BUSINESS,
    CREATE_CUSTOMER,
    POINTS_BY_CUSTOMER_EMAIL,
    EDIT_BUSINESS
}
