package com.customify.server;

public enum Keys {
    LOGIN,
    REGISTER,
    FEEDBACK,
    GET_USERS,
    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    DELETE_PRODUCT,
    GET_PRODUCT_BY_ID,
    UPDATE_PRODUCT,
    CREATE_BUSINESS,
    REMOVE_BUSINESS,
    GET_ALL_BUSINESSES,
    GET_BUSINESS,
    CREATE_CUSTOMER,
    EDIT_BUSINESS,
<<<<<<< HEAD
    CREATE_PLAN,
    UPDATE_PLAN,
    READ_PLAN,
    DELETE_PLAN
=======
    DISABLE_CUSTOMER,
    POINTS_BY_CUSTOMER_EMAIL,
    EDIT_BUSINESS
>>>>>>> 07d7c967a8dcf9ed257a4d668f4a21968cfece23
}
