package com.customify.server;

public enum Keys {
    LOGIN,
    REGISTER,
    FEEDBACK,
    GET_USERS,
    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    DELETE_PRODUCT,
    GET_WINNERS,
    POINTS_BY_CUSTOMER_EMAIL,
    GET_PRODUT_BY_ID,
    CREATE_BUSINESS,
    CREATE_CUSTOMER,
    EDIT_BUSINESS
}
